# Generated by Django 3.2.5 on 2021-07-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(db_index=True, max_length=165, unique=True)),
                ('slug', models.SlugField(max_length=165, unique=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
