# Generated by Django 3.2.5 on 2021-07-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsBlog', '0002_auto_20210727_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='newsBlog.Tag'),
        ),
    ]
